-- GymMasterAppDemo: synthetic transactional seed with dates relative to execution day
-- Run files in numbered order using SQL Server tooling (GO batch separator).
SET NOCOUNT ON;
USE [GymMasterDBDemo];
GO
IF DB_NAME() COLLATE Latin1_General_100_BIN2 <> N'GymMasterDBDemo'
    THROW 51000, 'Demo safety check failed. Expected GymMasterDBDemo.', 1;
SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;
-- All transactional records below are synthetic. Re-running replaces only demo transactions.
-- Identity values are generated by SQL Server; maps preserve exported relationships.
DECLARE @Today date = CONVERT(date, GETDATE());
DECLARE @Now datetime2(0) = SYSDATETIME();
DECLARE @HealthRecordIdMap TABLE (SourceId bigint PRIMARY KEY, NewId bigint NOT NULL);
DECLARE @MembershipIdMap TABLE (SourceId bigint PRIMARY KEY, NewId bigint NOT NULL);
DECLARE @ProgramsWorkoutIdMap TABLE (SourceId bigint PRIMARY KEY, NewId bigint NOT NULL);
DELETE FROM [dbo].[ProgramsWorkoutDetails];
DELETE FROM [dbo].[Payments];
DELETE FROM [dbo].[ProgramsWorkout];
DELETE FROM [dbo].[Membership];
DELETE FROM [dbo].[Customers];
DELETE FROM [dbo].[HealthRecord];

-- HealthRecord: 12 synthetic records.
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 01', N'0000000101', N'Synthetic demo health record.');
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (1, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (1, N'Περιστασιακή ενόχληση στη μέση.', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, N'Ήπια ενόχληση στη μέση.', 0, NULL, N'Demo Contact 02', N'0000000102', N'Demo data only.');
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (2, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 03', N'0000000103', NULL);
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (3, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 04', N'0000000104', N'Synthetic record.');
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (4, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 05', N'0000000105', NULL);
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (5, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 06', N'0000000106', NULL);
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (6, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 07', N'0000000107', N'Ελεγχόμενο demo ιστορικό.');
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (7, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 08', N'0000000108', NULL);
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (8, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (1, N'Ήπια ενόχληση στο γόνατο.', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, N'Παλαιότερη ενόχληση γόνατος.', 0, NULL, N'Demo Contact 09', N'0000000109', N'Demo record.');
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (9, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, NULL, 0, NULL, N'Demo Contact 10', N'0000000110', NULL);
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (10, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 11', N'0000000111', NULL);
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (11, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[HealthRecord] ([HasBodyPain], [BodyPainDesc], [IsObest], [IsSmoker], [FamilyHeartHistory], [HasHypertasis], [HasDiabetes], [HasHeartIssues], [HasAsthma], [HasThyroedes], [HasArthritis], [HasOsteoporosis], [HasAllergies], [HasMyosceletic], [MyoskeleticDesc], [HasOther], [OtherDesc], [EmergencyContact], [EmergencyPhone], [Comment])
VALUES (0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, NULL, N'Demo Contact 12', N'0000000112', NULL);
INSERT INTO @HealthRecordIdMap (SourceId, NewId) VALUES (12, CONVERT(bigint, SCOPE_IDENTITY()));

-- Customers: 25 synthetic records.
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10001, N'Demo01', N'Customer01', N'Demo Parent', N'1990-03-15', N'Α', N'1002', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 1), N'Demo Street 1', N'Demo City', NULL, N'0000000001', N'demo01@example.com', 1, DATEADD(DAY, -4, @Now), N'Synthetic portfolio customer.');
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10002, N'Demo02', N'Customer02', N'Demo Parent', N'1988-07-10', N'Γ', N'1001', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 2), N'Demo Street 2', N'Demo City', NULL, N'0000000002', N'demo02@example.com', 1, DATEADD(DAY, -7, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10003, N'Demo03', N'Customer03', NULL, N'1995-11-22', N'Α', N'1003', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 3), N'Demo Street 3', N'Demo City', NULL, N'0000000003', N'demo03@example.com', 1, DATEADD(DAY, -12, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10004, N'Demo04', N'Customer04', NULL, N'1998-02-08', N'Γ', N'1000', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 4), N'Demo Street 4', N'Demo City', NULL, N'0000000004', N'demo04@example.com', 1, DATEADD(DAY, -18, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10005, N'Demo05', N'Customer05', NULL, N'1985-05-17', N'Α', N'1002', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 5), N'Demo Street 5', N'Demo City', NULL, N'0000000005', N'demo05@example.com', 1, DATEADD(DAY, -25, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10006, N'Demo06', N'Customer06', NULL, N'1992-09-30', N'Γ', N'1003', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 6), N'Demo Street 6', N'Demo City', NULL, N'0000000006', N'demo06@example.com', 1, DATEADD(DAY, -2, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10007, N'Demo07', N'Customer07', NULL, N'1996-01-14', N'Α', N'1004', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 7), N'Demo Street 7', N'Demo City', NULL, N'0000000007', N'demo07@example.com', 1, DATEADD(DAY, -9, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10008, N'Demo08', N'Customer08', NULL, N'1989-06-06', N'Γ', N'1001', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 8), N'Demo Street 8', N'Demo City', NULL, N'0000000008', N'demo08@example.com', 1, DATEADD(DAY, -15, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10009, N'Demo09', N'Customer09', NULL, N'1993-04-01', N'Α', N'1002', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 9), N'Demo Street 9', N'Demo City', NULL, N'0000000009', N'demo09@example.com', 1, DATEADD(DAY, -20, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10010, N'Demo10', N'Customer10', NULL, N'1991-12-12', N'Γ', N'1003', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 10), N'Demo Street 10', N'Demo City', NULL, N'0000000010', N'demo10@example.com', 1, DATEADD(DAY, -28, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10011, N'Demo11', N'Customer11', NULL, N'1984-03-02', N'Α', N'1001', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 11), N'Demo Street 11', N'Demo City', NULL, N'0000000011', N'demo11@example.com', 1, DATEADD(DAY, -61, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10012, N'Demo12', N'Customer12', NULL, N'1997-08-19', N'Γ', N'1000', (SELECT NewId FROM @HealthRecordIdMap WHERE SourceId = 12), N'Demo Street 12', N'Demo City', NULL, N'0000000012', N'demo12@example.com', 1, DATEADD(DAY, -92, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10013, N'Demo13', N'Customer13', NULL, N'1986-10-21', N'Α', N'1003', NULL, N'Demo Street 13', N'Demo City', NULL, N'0000000013', N'demo13@example.com', 1, DATEADD(DAY, -122, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10014, N'Demo14', N'Customer14', NULL, N'1994-04-18', N'Γ', N'1002', NULL, N'Demo Street 14', N'Demo City', NULL, N'0000000014', N'demo14@example.com', 1, DATEADD(DAY, -153, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10015, N'Demo15', N'Customer15', NULL, N'1982-09-05', N'Α', N'1001', NULL, N'Demo Street 15', N'Demo City', NULL, N'0000000015', N'demo15@example.com', 1, DATEADD(DAY, -183, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10016, N'Demo16', N'Customer16', NULL, N'2000-01-25', N'Γ', N'1000', NULL, N'Demo Street 16', N'Demo City', NULL, N'0000000016', N'demo16@example.com', 1, DATEADD(DAY, -214, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10017, N'Demo17', N'Customer17', NULL, N'1987-11-09', N'Α', N'1004', NULL, N'Demo Street 17', N'Demo City', NULL, N'0000000017', N'demo17@example.com', 1, DATEADD(DAY, -242, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10018, N'Demo18', N'Customer18', NULL, N'1999-05-13', N'Γ', N'1002', NULL, N'Demo Street 18', N'Demo City', NULL, N'0000000018', N'demo18@example.com', 1, DATEADD(DAY, -273, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10019, N'Demo19', N'Customer19', NULL, N'1990-07-27', N'Α', N'1003', NULL, N'Demo Street 19', N'Demo City', NULL, N'0000000019', N'demo19@example.com', 1, DATEADD(DAY, -304, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10020, N'Demo20', N'Customer20', NULL, N'1996-03-11', N'Γ', N'1001', NULL, N'Demo Street 20', N'Demo City', NULL, N'0000000020', N'demo20@example.com', 1, DATEADD(DAY, -334, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10021, N'Demo21', N'Customer21', NULL, N'1989-01-30', N'Α', N'1002', NULL, N'Demo Street 21', N'Demo City', NULL, N'0000000021', N'demo21@example.com', 1, DATEADD(DAY, -365, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10022, N'Demo22', N'Customer22', NULL, N'1995-06-24', N'Γ', N'1004', NULL, N'Demo Street 22', N'Demo City', NULL, N'0000000022', N'demo22@example.com', 1, DATEADD(DAY, -426, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10023, N'Demo23', N'Customer23', NULL, N'1983-02-16', N'Α', N'1003', NULL, N'Demo Street 23', N'Demo City', NULL, N'0000000023', N'demo23@example.com', 1, DATEADD(DAY, -487, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10024, N'Demo24', N'Customer24', NULL, N'1998-12-03', N'Γ', N'1000', NULL, N'Demo Street 24', N'Demo City', NULL, N'0000000024', N'demo24@example.com', 1, DATEADD(DAY, -548, @Now), NULL);
INSERT INTO [dbo].[Customers] ([Id], [LastName], [FirstName], [FatherName], [Birthday], [Gender], [OccupationId], [HealthId], [Address], [City], [Home], [Mobile], [Email], [Status], [CreationDate], [Comments])
VALUES (10025, N'Demo25', N'Customer25', NULL, N'1991-08-08', N'Α', N'1002', NULL, N'Demo Street 25', N'Demo City', NULL, N'0000000025', N'demo25@example.com', 0, DATEADD(DAY, -607, @Now), N'Inactive synthetic demo customer.');

-- Membership: 20 synthetic records.
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10001, N'100', N'ΜΗ01', 30, DATEADD(DAY, -30, @Today), DATEADD(DAY, 0, @Today), 40.00, N'1', N'Demo membership ending today', DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (1, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10002, N'101', N'ΜΗ01', 30, DATEADD(DAY, -30, @Today), DATEADD(DAY, 0, @Today), 45.00, N'0', N'Demo unpaid membership ending today', DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (2, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10003, N'104', N'ΜΗ03', 90, DATEADD(DAY, -90, @Today), DATEADD(DAY, 0, @Today), 120.00, N'2', N'Demo pending membership ending today', DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (3, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10004, N'103', N'ΜΗ01', 30, DATEADD(DAY, -10, @Today), DATEADD(DAY, 20, @Today), 55.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (4, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10005, N'100', N'ΜΗ03', 90, DATEADD(DAY, -20, @Today), DATEADD(DAY, 70, @Today), 100.00, N'0', N'Partial payment demo', DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (5, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10006, N'104', N'ΜΗ01', 30, DATEADD(DAY, -5, @Today), DATEADD(DAY, 25, @Today), 60.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (6, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10007, N'101', N'ΜΗ01', 30, DATEADD(DAY, -15, @Today), DATEADD(DAY, 15, @Today), 45.00, N'0', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (7, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10008, N'103', N'ΜΗ03', 90, DATEADD(DAY, -40, @Today), DATEADD(DAY, 50, @Today), 130.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (8, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10009, N'100', N'ΜΗ12', 365, DATEADD(DAY, -100, @Today), DATEADD(DAY, 265, @Today), 360.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (9, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10010, N'104', N'ΜΗ01', 30, DATEADD(DAY, -8, @Today), DATEADD(DAY, 22, @Today), 65.00, N'2', N'Payment complete, status pending', DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (10, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10011, N'100', N'ΜΗ01', 30, DATEADD(DAY, -80, @Today), DATEADD(DAY, -50, @Today), 40.00, N'1', NULL, DATEADD(DAY, -80, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (11, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10012, N'101', N'ΜΗ03', 90, DATEADD(DAY, -150, @Today), DATEADD(DAY, -60, @Today), 120.00, N'1', NULL, DATEADD(DAY, -150, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (12, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10013, N'103', N'ΜΗ01', 30, DATEADD(DAY, -45, @Today), DATEADD(DAY, -15, @Today), 50.00, N'0', N'Expired unpaid demo record', DATEADD(DAY, -45, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (13, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10014, N'100', N'ΜΗ03', 90, DATEADD(DAY, -30, @Today), DATEADD(DAY, 60, @Today), 105.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (14, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10015, N'104', N'ΜΗ01', 30, DATEADD(DAY, -3, @Today), DATEADD(DAY, 27, @Today), 65.00, N'0', N'New unpaid membership', DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (15, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10016, N'100', N'ΗΜ01', 1, DATEADD(DAY, 0, @Today), DATEADD(DAY, 1, @Today), 8.00, N'1', N'Daily demo membership', DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (16, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10017, N'101', N'ΜΗ03', 90, DATEADD(DAY, -25, @Today), DATEADD(DAY, 65, @Today), 120.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (17, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10018, N'103', N'ΜΗ01', 30, DATEADD(DAY, -12, @Today), DATEADD(DAY, 18, @Today), 50.00, N'0', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (18, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10019, N'100', N'ΜΗ12', 365, DATEADD(DAY, -200, @Today), DATEADD(DAY, 165, @Today), 350.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (19, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[Membership] ([CustomerId], [ServiceCode], [MembershipType], [Duration], [StartDate], [EndDate], [Price], [StatusCode], [Comment], [CreationDate])
VALUES (10020, N'104', N'ΜΗ03', 90, DATEADD(DAY, -35, @Today), DATEADD(DAY, 55, @Today), 140.00, N'1', NULL, DATEADD(DAY, 0, @Now));
INSERT INTO @MembershipIdMap (SourceId, NewId) VALUES (20, CONVERT(bigint, SCOPE_IDENTITY()));

-- Payments: 23 synthetic records.
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 1), DATEADD(DAY, -30, @Today), N'10:00:00', N'00', 40.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 2), DATEADD(DAY, -30, @Today), N'11:00:00', N'10', 20.00, DATEADD(DAY, 0, @Now), N'Partial demo payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 3), DATEADD(DAY, -90, @Today), N'12:00:00', N'20', 120.00, DATEADD(DAY, 0, @Now), N'Paid amount; membership intentionally pending');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 4), DATEADD(DAY, -10, @Today), N'09:15:00', N'10', 55.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 5), DATEADD(DAY, -20, @Today), N'18:00:00', N'00', 20.00, DATEADD(DAY, 0, @Now), N'First partial payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 5), DATEADD(DAY, -10, @Today), N'18:15:00', N'10', 20.00, DATEADD(DAY, 0, @Now), N'Second partial payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 6), DATEADD(DAY, -5, @Today), N'17:30:00', N'10', 60.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 7), DATEADD(DAY, -15, @Today), N'13:20:00', N'00', 15.00, DATEADD(DAY, 0, @Now), N'First partial payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 7), DATEADD(DAY, -5, @Today), N'15:00:00', N'10', 10.00, DATEADD(DAY, 0, @Now), N'Second partial payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 8), DATEADD(DAY, -40, @Today), N'16:00:00', N'20', 130.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 9), DATEADD(DAY, -100, @Today), N'10:30:00', N'10', 360.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 10), DATEADD(DAY, -8, @Today), N'14:10:00', N'10', 65.00, DATEADD(DAY, 0, @Now), N'Pending status demo');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 11), DATEADD(DAY, -80, @Today), N'11:30:00', N'00', 40.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 12), DATEADD(DAY, -150, @Today), N'12:30:00', N'20', 120.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 13), DATEADD(DAY, -45, @Today), N'18:20:00', N'00', 20.00, DATEADD(DAY, 0, @Now), N'Expired unpaid demo');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 14), DATEADD(DAY, -30, @Today), N'09:50:00', N'10', 105.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 15), DATEADD(DAY, -3, @Today), N'17:10:00', N'00', 20.00, DATEADD(DAY, 0, @Now), N'First partial payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 15), DATEADD(DAY, -1, @Today), N'17:30:00', N'10', 15.00, DATEADD(DAY, 0, @Now), N'Second partial payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 16), DATEADD(DAY, 0, @Today), N'08:30:00', N'00', 8.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 17), DATEADD(DAY, -25, @Today), N'19:00:00', N'20', 120.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 18), DATEADD(DAY, -12, @Today), N'18:00:00', N'10', 25.00, DATEADD(DAY, 0, @Now), N'Partial payment');
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 19), DATEADD(DAY, -200, @Today), N'10:10:00', N'20', 350.00, DATEADD(DAY, 0, @Now), NULL);
INSERT INTO [dbo].[Payments] ([MembershipId], [PaymentDate], [PaymentTime], [MethodType], [Amount], [CreationDate], [Comment])
VALUES ((SELECT NewId FROM @MembershipIdMap WHERE SourceId = 20), DATEADD(DAY, -35, @Today), N'17:45:00', N'10', 140.00, DATEADD(DAY, 0, @Now), NULL);

-- ProgramsWorkout: 8 synthetic records.
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10001, N'Π000', 3, DATEADD(DAY, -7, @Today), DATEADD(DAY, 49, @Today), N'Synthetic demo workout program.', 8);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (1, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10002, N'Π001', 4, DATEADD(DAY, -14, @Today), DATEADD(DAY, 42, @Today), N'Demo program.', 8);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (2, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10003, N'Π002', 3, DATEADD(DAY, 0, @Today), DATEADD(DAY, 42, @Today), NULL, 6);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (3, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10004, N'Π003', 4, DATEADD(DAY, -5, @Today), DATEADD(DAY, 51, @Today), NULL, 8);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (4, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10005, N'Π004', 2, DATEADD(DAY, -10, @Today), DATEADD(DAY, 32, @Today), N'Maintenance demo program.', 6);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (5, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10006, N'Π000', 4, DATEADD(DAY, -3, @Today), DATEADD(DAY, 53, @Today), NULL, 8);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (6, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10007, N'Π002', 3, DATEADD(DAY, -20, @Today), DATEADD(DAY, 36, @Today), NULL, 8);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (7, CONVERT(bigint, SCOPE_IDENTITY()));
INSERT INTO [dbo].[ProgramsWorkout] ([CustomerId], [GoalCode], [Frequency], [StartDate], [EndDate], [Comments], [Duration])
VALUES (10008, N'Π003', 5, DATEADD(DAY, -8, @Today), DATEADD(DAY, 48, @Today), N'Demo endurance program.', 8);
INSERT INTO @ProgramsWorkoutIdMap (SourceId, NewId) VALUES (8, CONVERT(bigint, SCOPE_IDENTITY()));

-- ProgramsWorkoutDetails: 23 synthetic records.
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 1), N'ΔΚ10001', 3, 10, N'60 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 1), N'ΚΛ10001', 3, 15, N'45 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 1), N'ΔΚ10003', 3, 12, N'60 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 2), N'ΔΚ10002', 4, 12, N'45 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 2), N'ΚΛ10002', 3, 15, N'45 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 2), N'ΔΚ10004', 3, 10, N'60 sec', N'3η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 3), N'ΔΚ10001', 4, 6, N'90 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 3), N'ΔΚ10005', 4, 8, N'90 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 3), N'ΚΛ10003', 3, 12, N'60 sec', N'3η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 4), N'ΚΛ10001', 4, 20, N'30 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 4), N'ΚΛ10002', 4, 15, N'30 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 4), N'ΚΛ10003', 4, 15, N'30 sec', N'3η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 5), N'ΔΚ10003', 3, 12, N'60 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 5), N'ΚΛ10001', 3, 15, N'45 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 6), N'ΔΚ10001', 4, 10, N'60 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 6), N'ΔΚ10002', 4, 10, N'60 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 6), N'ΔΚ10005', 3, 12, N'60 sec', N'3η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 7), N'ΔΚ10003', 4, 8, N'90 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 7), N'ΔΚ10004', 4, 8, N'90 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 7), N'ΚΛ10003', 3, 12, N'60 sec', N'3η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 8), N'ΚΛ10001', 4, 20, N'30 sec', N'1η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 8), N'ΚΛ10002', 4, 20, N'30 sec', N'2η Μέρα');
INSERT INTO [dbo].[ProgramsWorkoutDetails] ([ProgramId], [ExerciseCode], [Sets], [Reps], [RestTime], [DayOfWeek])
VALUES ((SELECT NewId FROM @ProgramsWorkoutIdMap WHERE SourceId = 8), N'ΚΛ10003', 4, 15, N'30 sec', N'3η Μέρα');
IF (SELECT COUNT_BIG(*) FROM [dbo].[Customers]) <> 25
    THROW 51002, 'Unexpected synthetic row count: Customers.', 1;
IF (SELECT COUNT_BIG(*) FROM [dbo].[HealthRecord]) <> 12
    THROW 51002, 'Unexpected synthetic row count: HealthRecord.', 1;
IF (SELECT COUNT_BIG(*) FROM [dbo].[Membership]) <> 20
    THROW 51002, 'Unexpected synthetic row count: Membership.', 1;
IF (SELECT COUNT_BIG(*) FROM [dbo].[Payments]) <> 23
    THROW 51002, 'Unexpected synthetic row count: Payments.', 1;
IF (SELECT COUNT_BIG(*) FROM [dbo].[ProgramsWorkout]) <> 8
    THROW 51002, 'Unexpected synthetic row count: ProgramsWorkout.', 1;
IF (SELECT COUNT_BIG(*) FROM [dbo].[ProgramsWorkoutDetails]) <> 23
    THROW 51002, 'Unexpected synthetic row count: ProgramsWorkoutDetails.', 1;
IF EXISTS (SELECT 1 FROM dbo.Customers WHERE Id < 10001 OR Id > 10025)
    THROW 51003, 'Unexpected synthetic customer ID.', 1;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
